name: Lint and Publish
on: push
jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "todo"
          npm install
          npm run lint
    name: publish
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: JS-DevTools/npm-publish@v1 actions/checkout@v2
        with:
          registry: https://npm.pkg.github.com
          token: ${{ secrets.GITHUB_TOKEN }}
