name: Lint and Publish
on: push
jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn install
          yarn lint
  publish:
    name: Publish to github package registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "TODO:"
